/* Autogenerated file. Do not edit manually. */

/* eslint-disable max-classes-per-file */
/* eslint-disable @typescript-eslint/no-unused-vars */
/* eslint-disable @typescript-eslint/consistent-type-imports */

/*
  Fuels version: 0.99.0
*/

import { Contract as __Contract, Interface } from "fuels";
import type {
  Provider,
  Account,
  StorageSlot,
  Address,
  BigNumberish,
  BN,
  FunctionFragment,
  InvokeFunction,
} from 'fuels';

export type G1PointInput = { x: BigNumberish, y: BigNumberish };
export type G1PointOutput = { x: BN, y: BN };
export type ProofInput = { proof_A: G1PointInput, proof_B: G1PointInput, proof_C: G1PointInput, proof_Z: G1PointInput, proof_T1: G1PointInput, proof_T2: G1PointInput, proof_T3: G1PointInput, proof_Wxi: G1PointInput, proof_Wxiw: G1PointInput, eval_a: BigNumberish, eval_b: BigNumberish, eval_c: BigNumberish, eval_s1: BigNumberish, eval_s2: BigNumberish, eval_zw: BigNumberish };
export type ProofOutput = { proof_A: G1PointOutput, proof_B: G1PointOutput, proof_C: G1PointOutput, proof_Z: G1PointOutput, proof_T1: G1PointOutput, proof_T2: G1PointOutput, proof_T3: G1PointOutput, proof_Wxi: G1PointOutput, proof_Wxiw: G1PointOutput, eval_a: BN, eval_b: BN, eval_c: BN, eval_s1: BN, eval_s2: BN, eval_zw: BN };

const abi = {
  "programType": "contract",
  "specVersion": "1",
  "encodingVersion": "1",
  "concreteTypes": [
    {
      "type": "[u256; 1]",
      "concreteTypeId": "d260603a6118f4d090787a9d1cc94f3afade594c02f0049f0f856f4d5285d980",
      "metadataTypeId": 0
    },
    {
      "type": "bool",
      "concreteTypeId": "b760f44fa5965c2474a3b471467a22c43185152129295af588b022ae50b50903"
    },
    {
      "type": "struct lib::Proof",
      "concreteTypeId": "8a68b7127f274d82f168ea6210f2467884ef0410a7f5748dbff52b134a2c6c09",
      "metadataTypeId": 2
    }
  ],
  "metadataTypes": [
    {
      "type": "[_; 1]",
      "metadataTypeId": 0,
      "components": [
        {
          "name": "__array_element",
          "typeId": 3
        }
      ]
    },
    {
      "type": "struct lib::G1Point",
      "metadataTypeId": 1,
      "components": [
        {
          "name": "x",
          "typeId": 3
        },
        {
          "name": "y",
          "typeId": 3
        }
      ]
    },
    {
      "type": "struct lib::Proof",
      "metadataTypeId": 2,
      "components": [
        {
          "name": "proof_A",
          "typeId": 1
        },
        {
          "name": "proof_B",
          "typeId": 1
        },
        {
          "name": "proof_C",
          "typeId": 1
        },
        {
          "name": "proof_Z",
          "typeId": 1
        },
        {
          "name": "proof_T1",
          "typeId": 1
        },
        {
          "name": "proof_T2",
          "typeId": 1
        },
        {
          "name": "proof_T3",
          "typeId": 1
        },
        {
          "name": "proof_Wxi",
          "typeId": 1
        },
        {
          "name": "proof_Wxiw",
          "typeId": 1
        },
        {
          "name": "eval_a",
          "typeId": 3
        },
        {
          "name": "eval_b",
          "typeId": 3
        },
        {
          "name": "eval_c",
          "typeId": 3
        },
        {
          "name": "eval_s1",
          "typeId": 3
        },
        {
          "name": "eval_s2",
          "typeId": 3
        },
        {
          "name": "eval_zw",
          "typeId": 3
        }
      ]
    },
    {
      "type": "u256",
      "metadataTypeId": 3
    }
  ],
  "functions": [
    {
      "inputs": [
        {
          "name": "proof",
          "concreteTypeId": "8a68b7127f274d82f168ea6210f2467884ef0410a7f5748dbff52b134a2c6c09"
        },
        {
          "name": "pub_signal",
          "concreteTypeId": "d260603a6118f4d090787a9d1cc94f3afade594c02f0049f0f856f4d5285d980"
        }
      ],
      "name": "verify",
      "output": "b760f44fa5965c2474a3b471467a22c43185152129295af588b022ae50b50903",
      "attributes": null
    }
  ],
  "loggedTypes": [],
  "messagesTypes": [],
  "configurables": []
};

const storageSlots: StorageSlot[] = [];

export class SwayZkpExampleInterface extends Interface {
  constructor() {
    super(abi);
  }

  declare functions: {
    verify: FunctionFragment;
  };
}

export class SwayZkpExample extends __Contract {
  static readonly abi = abi;
  static readonly storageSlots = storageSlots;

  declare interface: SwayZkpExampleInterface;
  declare functions: {
    verify: InvokeFunction<[proof: ProofInput, pub_signal: [BigNumberish]], boolean>;
  };

  constructor(
    id: string | Address,
    accountOrProvider: Account | Provider,
  ) {
    super(id, abi, accountOrProvider);
  }
}
